# Generated by Django 4.2.1 on 2023-06-01 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='更新人')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsCategory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.basemodel')),
                ('name', models.CharField(max_length=128, verbose_name='分类名称')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_cat', to='assets.assetscategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '资产分类',
                'verbose_name_plural': '资产分类',
                'db_table': 'devops_category',
            },
            bases=('assets.basemodel',),
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.basemodel')),
                ('name', models.CharField(max_length=128, verbose_name='主机名称')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='主机地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('assets_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assetscategory', verbose_name='资产分类')),
            ],
            options={
                'verbose_name': '资产信息',
                'verbose_name_plural': '资产信息',
                'db_table': 'devops_assets',
            },
            bases=('assets.basemodel',),
        ),
    ]
