# Generated by Django 4.2.1 on 2023-05-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'verbose_name': '数据库信息', 'verbose_name_plural': '数据库信息'},
        ),
        migrations.AddField(
            model_name='database',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='database',
            name='host',
            field=models.CharField(max_length=255, verbose_name='主机地址'),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='database',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='database',
            name='port',
            field=models.IntegerField(default=3306, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='database',
            name='user',
            field=models.CharField(max_length=255, verbose_name='用户'),
        ),
        migrations.AlterModelTable(
            name='database',
            table='devops_databases',
        ),
    ]
